### ISSUE TITLE
Does not return all data

### ISSUE THREAD

**Issue by Agnaldo-MR** [BoardiesITSolutions/Android-MySQL-Connector#26] opened 2023-10-16 14:39 UTC
Hello Chris Board.

I have a problem with your MySQL connection API. Communication with the Database is carried out normally, but only part of the data is returned and without any errors. As if it were limiting the number of data, but without the Limit clause.
Already tried:
Select *.t From table t , Select * From table, Select t.campo1, t.campo2 From table t... with where clause and several other ways, but without success.

I haven't been able to observe it in all of them yet, but this occurs in two specific tables...

Can you help me, please?

![Config1](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/b5154f0b-75e0-4d36-be64-1c950193c3a8)

![Config2](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/e226a77b-6271-4614-966b-1be272a4a23c)

Error in one of the tables:

![image](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/d4d1770c-cd03-4ade-b918-a459cb7ec49d)

**Comment by boardy** [comment] 2023-10-16 17:11
Hi, Just to double check are you using the latest tag release with MySQL8 appended to the end of the tag name. Although you are using MySQL 5.x the MySQL8 appended tags is compatible and has numerous bug fixes that should fix this issue I believe. 

If you are can you confirm you are on the latest tag, and how many records are within your database table and how many are being returned by the library. 

Thanks
Chris

**Comment by Agnaldo-MR** [comment] 2023-10-16 19:10
By HeidiSQL
/* Records affected: 0 Records found: 589 Warnings: 0
API returned only 298 Records

Android: com.github.BoardiesITSolutions:Android-MySQL-Connector:0.49_MySQL8

Would this be above or how do I check this TAG?

**Comment by boardy** [comment] 2023-10-16 19:13
It does look like you are on the latest tag. 

I'll check it out not sure why that would be, it might take me a few days though unfortunately, as been a while since I've done any work on this project so haven't got the dev environment set up for it at the moment.

**Comment by Agnaldo-MR** [comment] 2023-10-16 19:15
Anyway, thank you for your feedback and I hope you can help me. Thanks.

**Comment by Agnaldo-MR** [comment] 2023-10-16 19:32
Adding information:
If I use it this way below it only returns 79 records. And indicating each field (Select a.value, a.description, a.active...) returns 298 records out of a total of 589.
query = "SELECT * " + (or "SELECT a.* ")
                "FROM table a " +
                "WHERE a.active = 'S' AND (a.type = 'D' OR a.type = 'E');";
executeMySql(query);

**Comment by boardy** [comment] 2023-10-18 17:23
Thanks for the extra info, that's very odd, not sure why the query style would affect how it returns the data in that way. 

I'm still in the process of building the dev environment, taking a little longer than I hoped as I can only work on it in my spare time.

**Comment by boardy** [comment] 2023-10-18 18:09
I've not been able to replicate it unfortunately. 

I've created a very basic table like below:

![image](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/4533555/de52f37b-5af9-44da-a061-d80d6d70ba3b)

This includes 800 rows.

When I connect to the database, I call a function called loopData which is the below:

```
public void loopData(boolean onlyPerformSelect)
    {
        Log.d("MainActivity", "Looping over data");
        Statement statement = mysqlConn.createStatement();
        statement.executeQuery("SELECT id, col, value FROM my_table t WHERE t.id > 10", new IResultInterface() {
            @Override
            public void executionComplete(ResultSet resultSet) {
                MySQLRow row;
                Log.d("MainActivity", "Returned Rows: " + resultSet.getNumRows());
                int id = 0;
                while ((row = resultSet.getNextRow()) != null)
                {
                    try {
                        id = row.getInt("id");
                        Log.d("MainActivity", "Got Result: " + String.valueOf(row.getInt("id")));
                    } catch (SQLColumnNotFoundException e) {
                        e.printStackTrace();
                    }
                }
              
            }
```

And the log cat output outputs every single row as expected. 

Before you start looping over the data, could you log out the value of the following 

`resultSet.getNumRows()`

And see if this returns the number of rows you are expecting to be returned, or just includes the number of rows that you actually see returned. 

Would it be possible to provide me an SQL file that includes the table definition with some sample data if possible - obviously don't give me any sensitive information. Can you also give me a rough size that this table is in terms of storage space on your server. 

I've tried with 8000 records as well and still seems to work OK, so wondering if its to do with the volume of the size of the data coming back, or potentially something in the database is causing the library to not parse the MySQL server correctly.

**Comment by Agnaldo-MR** [comment] 2023-10-20 12:47
Whether or not you use resultSet.getNumRows(), all records in the Android APP report are not returned.

I use a query in a string and pass it as a parameter, but I have already used a direct command like you did above in statement.executeQuery and the result was the same.

Follow the sql with the creation of the database and one of the tables with the problem.

It also follows the "limit" TAG of database limits. I don't know if it will help.
![Limites](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/ee910a89-e90e-4265-8914-ba61ad5d4590)

**Comment by boardy** [comment] 2023-10-21 11:48
Hi, 

I've imported your database file and have replicated the problem now. It looks like the library is detecting something as an SQL Error packet, but it's not and then throws an exception. 

Now that I've replicated, hopefully I'll be able to find out what's going wrong and get back to you with a new release in the not too distant future.

Thanks
Chris

**Comment by Agnaldo-MR** [comment] 2023-10-22 16:09
Just a note: the API already works perfectly in the version described below with mysql_native_password. I say this to ensure that changes do not interfere with what is already working perfectly. 

Thank you very much for your availability.

![Versao](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/329e6111-2f00-43d0-9cea-4c1826c77d46)

**Comment by boardy** [comment] 2023-10-22 16:10
Hi, 

This should be fixed now. If you change your Gradle file to use com.github.BoardiesITSolutions:Android-MySQL-Connector:0.52_MySQL8 and do a Gradle sync it should pick up the new version. 

Thanks
Chris

**Comment by Agnaldo-MR** [comment] 2023-10-22 23:13
The previous table worked, but this one attached still has a problem.

query = "SELECT * FROM pedido p WHERE p.setor LIKE 'S-%' AND p.idLoja = 12;";
                
connectMySql(query);

It should return 15 records, but it returns none and displays the error: Empty socket data was returned.

HeidiSQL returns normal.

Note: A connection to another independent database is opened and closed and a connection to the APP database is opened for the above query. Connection is also independent, each database has its own connection.

When I download the file, could I delete it?
Thank you again.

![Erro](https://github.com/BoardiesITSolutions/Android-MySQL-Connector/assets/62654732/abd01443-d379-46e8-b848-58e98aaa2435)

**Comment by boardy** [comment] 2023-10-23 10:42
Hi,

I've imported the SQL file you provided but I've not been able to replicate this particular problem. When I run the query and output the id column it outputs 15 rows from id 2796 through to 2810. 

You mentioned this table is in a different database connection, is it the same type of MySQL server as the previous one, or is it a different server such as different MySQL version for example?

**Comment by Agnaldo-MR** [comment] 2023-10-23 12:06
The APP first connects to the Mysql version 8 database mentioned above. He performs the query and then disconnects. Then it opens another connection to the Mysql database of the APP version 5 mentioned above in another comment. When you run this second query, it generates the error and returns nothing.

Remembering that they are distinct connections and implementation, all separate from each other.

Note: This works perfectly up to a certain number of records. After this limit, not specified yet, it generates the error. I can't say the number of records, as there are several users, but somewhere around 350 to 400 records. From then on it starts generating the error.

**Comment by boardy** [comment] 2023-10-23 13:00
Just to make sure I'm clear. The MySQL 5 table is working fine now, but the issue with the other table is on MySQL 8?

I tested both tables on MySQL 5.7 with two separate connections and it worked fine. The second table I also did a query to select everything, and got back a couple of thousand rows I think it was and then with the WHERE clause and got the 15 that you expected.

When you say two separate connections, do you create two separate MySQLConnection objects, one for each database, or do you create one mysql connection object. Close the connection on one database, and then update that same connection object with the new database connection?

**Comment by Agnaldo-MR** [comment] 2023-10-23 13:21
Not exactly. The mysql 5 worked on the first table and is not working on this second table. There is no problem, for now, with mysql 8.

The connection and also the execution of SQL I carry out through two completely separate MySQLConnection objects. From connection, execution and then closing the connection. Each process separate from each other, from beginning to end. One for mysql 5 and one for mysql 8.

In mysql 8 I perform a read-only query. And in mysql 5 I query and then record the final information. The error appears when executing the query in MySQL 5. With the error it is unable to insert the data after the reading process, to check the information before inserting.

**Comment by boardy** [comment] 2023-10-23 13:26
Hmmm, I'm not entirely sure what I can do here at the moment unfortunately. I'm not connecting to MySQL 8 in my tests, but if they are completely separate connections as far as the library is concerned then I don't really see how it could be related. 

I've run the query you provided on the second table and got the 15 records out you were expecting without any errors being thrown, so I can only guess there's some odd interaction going with the two connections within your app and the library somehow. 

Is it possible you could create a small demo app that would reproduce the problem, in the meantime I'll get a database set up on MySQL 8 and attempt connecting to that first.

**Comment by boardy** [comment] 2023-10-23 13:59
I've got it connected to MySQL 8 and then query the second table but still get all the data back as expected. 

I use the same MySQLConnection variable, just create it connecting to MySQL 8, then create a new object on the same variable connecting to MySQL 5.7 so unfortunately I'm not sure where the problem might be.

**Comment by Agnaldo-MR** [comment] 2023-10-23 14:12
I just carried out a test in this format

SELECT p.* FROM pedido p WHERE p.setor LIKE 'S-%' AND p.idLoja = 12;

This time it worked. I was using it before, specifying each field: p.idPedido, p.idProduto, p.nrPedido, p.codBarras...

I really don't know how to explain this error with different query formats and also because the error occurs after a certain number of launches. If the error continues, I will contact you again.

I greatly appreciate all your availability.

**Comment by boardy** [comment] 2023-10-23 14:21
I've done the query as `SELECT p.codigo, p.idPedido, p.idProduto, p.nrPedido, p.codBarras FROM pedido p WHERE p.setor LIKE 'S-%' AND p.idLoja = 12;` and that worked OK.

At what point does it fail, while you are looping over the date, or before the data being looped from the query. 

The only other thing I can think of, each time you execute a new SQL query do you do `Statement statement = mysqlConn.createStatement();` first for each query or are you sometimes using the same statement with a different query, that's the only other thing I could think of that might affect how the library accesses the database.

**Comment by Agnaldo-MR** [comment] 2023-10-23 15:03
Statement statement = mysqlConnection.createStatement();
         statement.executeQuery(query, new IResultInterface() {
             @Override
             public void executionComplete(ResultSet resultSet) {

It doesn't even enter to perform the loop. Executes the first line and the second generates the error: Empty socket data was returned.

The strange thing is that it works well, up to a certain number of records and then the error starts for all APPs on cell phones. Always for the last users who try to pass the request. Then, when I update the p.setor variable to 'N-HFG' in all products, to start a new process, the query is performed normally.

I think it's a database blocking of a certain number of records, on the same day and in the same table. I can't explain any more. I made countless attempts, always with the same result.

Sometimes it works by changing the format of the query text: Asterisk or describing each field individually. But, it doesn't always work. So much so that now I used p.* and it worked. Only God can explain...

And it's true. For each query a
Statement statement = mysqlConn.createStatement();
Then execute the insert and close the connection. I don't use the same statement.

**Comment by boardy** [comment] 2023-10-23 15:10
Very strange, technically, the format of the SQL query shouldn't affect how I get the data back from the MySQL server. If it changes seemingly randomly when the query format is changed, then I suspect there's some interaction going on somewhere within multiple queries within your app which is causing the problem within the library, although I can't seem to replicate any problem you are seeing which is odd. 

If you can create a small app that can replicate the problem then I can take another look, but without that I'm not sure I'm going to be able to see what's happening. 

Another alternative, although can't guarantee I'd be able to see exactly the cause this way but it might help, if you can do a LAN trace from the MySQL server but you would have to disable TLS on the server otherwise it would be encrypted and I wouldn't be able to see what was going on between the library and the server. 

Sorry I can't help much more than that unfortunately.

**Comment by Agnaldo-MR** [comment] 2023-10-23 15:15
What you did is already very good. Thank you very much. As soon as possible I will do the tests and I will get back to you with any news.

**Closed as completed** 2023-10-27 11:45 UTC
Labels: bug
