### ISSUE TITLE
Resulset is always empty

### ISSUE THREAD

**Issue by joellara445** [BoardiesITSolutions/Android-MySQL-Connector#6] opened 2019-01-19 16:36 UTC
It seems that the query is been send correctly because columnsize and title is correct,

But num of rows is always empty even when i request all data from the table.

**Comment by boardy** [comment] 2019-01-19 16:38
Hi, I'm going to need a bit more into to help with this. 

Can you give me an example of your DB and the query you are running, a snippet of the code that is performing the query and fetching the resultset and your MySQL server version?

**Comment by joellara445** [comment] 2019-01-19 17:01
Server version : mysql 5.5.54


 mysqlConnection = new Connection("sql3.freemysqlhosting.net", "username", "pass", 3306, "db", new IConnectionInterface()
        {
            @Override
            public void actionCompleted()
            {

                System.out.println("Estamos conectados en el app");
                new LongOperation().execute("");

                //You are now connected to the database
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException e)
            {
                //Handle the error
                System.out.println("El error es:"+e.getMessage());
            }

            @Override
            public void handleMySQLException(MySQLException e)
            {
                System.out.println("El error es:"+e.getMessage());
                //Handle the error
            }

            @Override
            public void handleIOException(IOException e)
            {
                //Handle the error
                System.out.println("El error es:"+e.getMessage());
            }

            @Override
            public void handleMySQLConnException(MySQLConnException e)
            {
                //Handle the error
                System.out.println("El error es:"+e.getMessage());
            }

            @Override
            public void handleException(Exception e)
            {
                //Handle the error
                System.out.println("El error es:"+e.getMessage());
            }
        });



QUERY:

final Statement statement = mysqlConnection.createStatement();
            statement.executeQuery("select * from clientes", new IResultInterface()
            {
                @Override
                public void executionComplete(ResultSet resultSet)
                {

                    System.out.println("RES "+resultSet.getNumRows());


                    MySQLRow row;
                    while ((row = resultSet.getNextRow()) != null)
                    {



                        try {
                            String telefono = row.getString("telefono");
                            System.out.println( "the phone is:"+telefono);
                        } catch (SQLColumnNotFoundException e) {

                            System.out.println("El error MYSQL "+e.getMessage());
                            e.printStackTrace();
                        }

                        //Read the row contents here
                    }





                }

                @Override
                public void handleInvalidSQLPacketException(InvalidSQLPacketException e)
                {
                    Log.e("DBViewFragment", e.toString());

                }

                @Override
                public void handleMySQLException(MySQLException e)
                {
                    Log.e("DBViewFragement", e.toString());

                }

                @Override
                public void handleIOException(IOException e)
                {
                    Log.e("DBViewFragement",e.toString());

                }

                @Override
                public void handleMySQLConnException(MySQLConnException e)
                {
                    Log.e("DBViewFragement", e.toString());

                }

                @Override
                public void handleException(Exception e)
                {
                    Log.e("DBViewFragement", e.toString());

                }
            });



Output numrows

01-19 11:58:41.803 30321-30359/com.nss.joel.pedidosa I/System.out: RES 0
01-19 11:58:41.965 30321-30359/com.nss.joel.pedidosa I/System.out: RES 0

**Comment by boardy** [comment] 2019-01-19 21:52
Hi, 

I've not been able to replicate this, although not on exactly the same MySQL version, I'm not a slightly version newer (5.5.59) so not sure if that's making the difference, so I'll give that a try if I can still get that MySQL version. 

What actions your select query to be done, is it from a button press or called straight after the connection is successfully made to the DB. 

Could you also post your logcat as this may contain some information as to give me a clue as to what's going on.

**Comment by boardy** [comment] 2019-01-19 21:57
It doesn't look like I can get MySQL 5.5.54 anymore, the earliest I can get is MySQL 5.5.62 so I'd probably recommend upgrading MySQL if possible, 5.5 is a very old version - if you do upgrade though, don't upgrade to MySQL 8 as the connector library is not supported yet unfortunately.

**Comment by joellara445** [comment] 2019-01-21 09:39
The query comes from a button inside of a fragment, no error visible on logcat. Could be possible callback return with no visible error?.

**Comment by boardy** [comment] 2019-01-21 09:54
Hmm strange, not that I am aware of, the only thing I can think of is this particular version of MySQL has a slightly different packet structure (I've noticed that between versions) so I might not be parsing the number of rows returned correctly, even if I am create a list of rows. 

I'll see if I can find a download for your specific MySQL version as its not on MySQL website anymore and have a look.

**Comment by joellara445** [comment] 2019-01-21 13:14
These are the logs that appear after button click

01-21 08:12:46.031 11872-11909/com.nss.joel.pedidosa D/Connection: Packet Sequence Number Returned: 0
01-21 08:12:46.032 11872-11909/com.nss.joel.pedidosa D/MySQLIO: Resetting Socket: Don't Expect Response: false
    Reading Socket Data
    Created baos
01-21 08:12:46.092 2780-2798/? E/MP-Decision: Update arg 1
01-21 08:12:46.176 11872-11909/com.nss.joel.pedidosa D/MySQLIO: Read from socket. Bytes Read: 802
    BAOS written: Bytes Written: 802
01-21 08:12:46.177 11872-11909/com.nss.joel.pedidosa D/MySQLIO: Breaking from loop
    Loop compleeted
    Full data written to: now size: 802

**Comment by boardy** [comment] 2019-01-21 19:15
Hi, I've managed to install MySQL 5.5.54 on a server and got the connector to connector to it and it worked fine with it returning data and providing the number of rows in the resultset. 

I've saw your using a freemysqlhost service which I've signed up to but I seem to be getting slightly different results to you. I'm only getting the column definitions from the SELECT statement, I'm not receiving the actual rows that I can loop over so not sure why its behaving differently to you. 

I'm still investigating the issue. 

Thanks

Chris

**Comment by boardy** [comment] 2019-01-21 19:34
Hello again, I think I've figured out where the issue is, the service you are using shows the MySQL version in a slightly different version than if you install it from a MySQL RPM - so because of that the library is taking the code path when its checking the MySQL version so its processing the resultset incorrectly. 

I'm working on a fix for this now and hope to get a release out as soon as I can. 

Thanks for your patience while I've been figuring out this issue.

**Comment by boardy** [comment] 2019-01-22 18:04
Hi, I've just pushed a new release to fix this issue. If you update your modules build.project to use 0.25 of the library instead and do a gradle sync and clean and rebuild you should be OK. 

Let me know how you get on. 

Thanks

Chris

**Comment by boardy** [comment] 2019-01-25 21:29
No feedback so closing - will reopen if required

**Closed as completed by boardy** 2019-01-25 21:29 UTC
Labels: bug
